name: WorldEditBlockParticles
version: "1.0.0"
author: "MrKitty_Cat"
api-version: 1.20
main: dev.twelveoclock.worldeditblockparticles.WorldEditBlockParticlesPlugin

commands:
  blockparticles:
    usage: "/blockparticles"
    description: "Toggles block particles"
