// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

public interface BlockParticlesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:store.BlockParticles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 tickRate = 1;</code>
   * @return The tickRate.
   */
  int getTickRate();

  /**
   * <code>.store.UUID worldUUID = 2;</code>
   * @return Whether the worldUUID field is set.
   */
  boolean hasWorldUUID();
  /**
   * <code>.store.UUID worldUUID = 2;</code>
   * @return The worldUUID.
   */
  dev.twelveoclock.worldeditblockparticles.proto.UUID getWorldUUID();
  /**
   * <code>.store.UUID worldUUID = 2;</code>
   */
  dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder getWorldUUIDOrBuilder();

  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  java.util.List<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle> 
      getBlockParticlesList();
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  dev.twelveoclock.worldeditblockparticles.proto.BlockParticle getBlockParticles(int index);
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  int getBlockParticlesCount();
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  java.util.List<? extends dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder> 
      getBlockParticlesOrBuilderList();
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder getBlockParticlesOrBuilder(
      int index);
}
