// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

/**
 * Protobuf type {@code store.BlockParticles}
 */
public final class BlockParticles extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:store.BlockParticles)
    BlockParticlesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockParticles.newBuilder() to construct.
  private BlockParticles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockParticles() {
    blockParticles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockParticles();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_BlockParticles_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_BlockParticles_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.class, dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.Builder.class);
  }

  private int bitField0_;
  public static final int TICKRATE_FIELD_NUMBER = 1;
  private int tickRate_ = 0;
  /**
   * <code>uint32 tickRate = 1;</code>
   * @return The tickRate.
   */
  @java.lang.Override
  public int getTickRate() {
    return tickRate_;
  }

  public static final int WORLDUUID_FIELD_NUMBER = 2;
  private dev.twelveoclock.worldeditblockparticles.proto.UUID worldUUID_;
  /**
   * <code>.store.UUID worldUUID = 2;</code>
   * @return Whether the worldUUID field is set.
   */
  @java.lang.Override
  public boolean hasWorldUUID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.store.UUID worldUUID = 2;</code>
   * @return The worldUUID.
   */
  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.UUID getWorldUUID() {
    return worldUUID_ == null ? dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance() : worldUUID_;
  }
  /**
   * <code>.store.UUID worldUUID = 2;</code>
   */
  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder getWorldUUIDOrBuilder() {
    return worldUUID_ == null ? dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance() : worldUUID_;
  }

  public static final int BLOCKPARTICLES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle> blockParticles_;
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle> getBlockParticlesList() {
    return blockParticles_;
  }
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder> 
      getBlockParticlesOrBuilderList() {
    return blockParticles_;
  }
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  @java.lang.Override
  public int getBlockParticlesCount() {
    return blockParticles_.size();
  }
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle getBlockParticles(int index) {
    return blockParticles_.get(index);
  }
  /**
   * <code>repeated .store.BlockParticle blockParticles = 3;</code>
   */
  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder getBlockParticlesOrBuilder(
      int index) {
    return blockParticles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tickRate_ != 0) {
      output.writeUInt32(1, tickRate_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getWorldUUID());
    }
    for (int i = 0; i < blockParticles_.size(); i++) {
      output.writeMessage(3, blockParticles_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tickRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, tickRate_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getWorldUUID());
    }
    for (int i = 0; i < blockParticles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, blockParticles_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.twelveoclock.worldeditblockparticles.proto.BlockParticles)) {
      return super.equals(obj);
    }
    dev.twelveoclock.worldeditblockparticles.proto.BlockParticles other = (dev.twelveoclock.worldeditblockparticles.proto.BlockParticles) obj;

    if (getTickRate()
        != other.getTickRate()) return false;
    if (hasWorldUUID() != other.hasWorldUUID()) return false;
    if (hasWorldUUID()) {
      if (!getWorldUUID()
          .equals(other.getWorldUUID())) return false;
    }
    if (!getBlockParticlesList()
        .equals(other.getBlockParticlesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TICKRATE_FIELD_NUMBER;
    hash = (53 * hash) + getTickRate();
    if (hasWorldUUID()) {
      hash = (37 * hash) + WORLDUUID_FIELD_NUMBER;
      hash = (53 * hash) + getWorldUUID().hashCode();
    }
    if (getBlockParticlesCount() > 0) {
      hash = (37 * hash) + BLOCKPARTICLES_FIELD_NUMBER;
      hash = (53 * hash) + getBlockParticlesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.twelveoclock.worldeditblockparticles.proto.BlockParticles prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code store.BlockParticles}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:store.BlockParticles)
      dev.twelveoclock.worldeditblockparticles.proto.BlockParticlesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_BlockParticles_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_BlockParticles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.class, dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.Builder.class);
    }

    // Construct using dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWorldUUIDFieldBuilder();
        getBlockParticlesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tickRate_ = 0;
      worldUUID_ = null;
      if (worldUUIDBuilder_ != null) {
        worldUUIDBuilder_.dispose();
        worldUUIDBuilder_ = null;
      }
      if (blockParticlesBuilder_ == null) {
        blockParticles_ = java.util.Collections.emptyList();
      } else {
        blockParticles_ = null;
        blockParticlesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_BlockParticles_descriptor;
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticles getDefaultInstanceForType() {
      return dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.getDefaultInstance();
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticles build() {
      dev.twelveoclock.worldeditblockparticles.proto.BlockParticles result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticles buildPartial() {
      dev.twelveoclock.worldeditblockparticles.proto.BlockParticles result = new dev.twelveoclock.worldeditblockparticles.proto.BlockParticles(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(dev.twelveoclock.worldeditblockparticles.proto.BlockParticles result) {
      if (blockParticlesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          blockParticles_ = java.util.Collections.unmodifiableList(blockParticles_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.blockParticles_ = blockParticles_;
      } else {
        result.blockParticles_ = blockParticlesBuilder_.build();
      }
    }

    private void buildPartial0(dev.twelveoclock.worldeditblockparticles.proto.BlockParticles result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tickRate_ = tickRate_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.worldUUID_ = worldUUIDBuilder_ == null
            ? worldUUID_
            : worldUUIDBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.twelveoclock.worldeditblockparticles.proto.BlockParticles) {
        return mergeFrom((dev.twelveoclock.worldeditblockparticles.proto.BlockParticles)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.twelveoclock.worldeditblockparticles.proto.BlockParticles other) {
      if (other == dev.twelveoclock.worldeditblockparticles.proto.BlockParticles.getDefaultInstance()) return this;
      if (other.getTickRate() != 0) {
        setTickRate(other.getTickRate());
      }
      if (other.hasWorldUUID()) {
        mergeWorldUUID(other.getWorldUUID());
      }
      if (blockParticlesBuilder_ == null) {
        if (!other.blockParticles_.isEmpty()) {
          if (blockParticles_.isEmpty()) {
            blockParticles_ = other.blockParticles_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBlockParticlesIsMutable();
            blockParticles_.addAll(other.blockParticles_);
          }
          onChanged();
        }
      } else {
        if (!other.blockParticles_.isEmpty()) {
          if (blockParticlesBuilder_.isEmpty()) {
            blockParticlesBuilder_.dispose();
            blockParticlesBuilder_ = null;
            blockParticles_ = other.blockParticles_;
            bitField0_ = (bitField0_ & ~0x00000004);
            blockParticlesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlockParticlesFieldBuilder() : null;
          } else {
            blockParticlesBuilder_.addAllMessages(other.blockParticles_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              tickRate_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getWorldUUIDFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              dev.twelveoclock.worldeditblockparticles.proto.BlockParticle m =
                  input.readMessage(
                      dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.parser(),
                      extensionRegistry);
              if (blockParticlesBuilder_ == null) {
                ensureBlockParticlesIsMutable();
                blockParticles_.add(m);
              } else {
                blockParticlesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int tickRate_ ;
    /**
     * <code>uint32 tickRate = 1;</code>
     * @return The tickRate.
     */
    @java.lang.Override
    public int getTickRate() {
      return tickRate_;
    }
    /**
     * <code>uint32 tickRate = 1;</code>
     * @param value The tickRate to set.
     * @return This builder for chaining.
     */
    public Builder setTickRate(int value) {

      tickRate_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 tickRate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTickRate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tickRate_ = 0;
      onChanged();
      return this;
    }

    private dev.twelveoclock.worldeditblockparticles.proto.UUID worldUUID_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.twelveoclock.worldeditblockparticles.proto.UUID, dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder, dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder> worldUUIDBuilder_;
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     * @return Whether the worldUUID field is set.
     */
    public boolean hasWorldUUID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     * @return The worldUUID.
     */
    public dev.twelveoclock.worldeditblockparticles.proto.UUID getWorldUUID() {
      if (worldUUIDBuilder_ == null) {
        return worldUUID_ == null ? dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance() : worldUUID_;
      } else {
        return worldUUIDBuilder_.getMessage();
      }
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    public Builder setWorldUUID(dev.twelveoclock.worldeditblockparticles.proto.UUID value) {
      if (worldUUIDBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        worldUUID_ = value;
      } else {
        worldUUIDBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    public Builder setWorldUUID(
        dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder builderForValue) {
      if (worldUUIDBuilder_ == null) {
        worldUUID_ = builderForValue.build();
      } else {
        worldUUIDBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    public Builder mergeWorldUUID(dev.twelveoclock.worldeditblockparticles.proto.UUID value) {
      if (worldUUIDBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          worldUUID_ != null &&
          worldUUID_ != dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance()) {
          getWorldUUIDBuilder().mergeFrom(value);
        } else {
          worldUUID_ = value;
        }
      } else {
        worldUUIDBuilder_.mergeFrom(value);
      }
      if (worldUUID_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    public Builder clearWorldUUID() {
      bitField0_ = (bitField0_ & ~0x00000002);
      worldUUID_ = null;
      if (worldUUIDBuilder_ != null) {
        worldUUIDBuilder_.dispose();
        worldUUIDBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder getWorldUUIDBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getWorldUUIDFieldBuilder().getBuilder();
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder getWorldUUIDOrBuilder() {
      if (worldUUIDBuilder_ != null) {
        return worldUUIDBuilder_.getMessageOrBuilder();
      } else {
        return worldUUID_ == null ?
            dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance() : worldUUID_;
      }
    }
    /**
     * <code>.store.UUID worldUUID = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.twelveoclock.worldeditblockparticles.proto.UUID, dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder, dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder> 
        getWorldUUIDFieldBuilder() {
      if (worldUUIDBuilder_ == null) {
        worldUUIDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.twelveoclock.worldeditblockparticles.proto.UUID, dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder, dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder>(
                getWorldUUID(),
                getParentForChildren(),
                isClean());
        worldUUID_ = null;
      }
      return worldUUIDBuilder_;
    }

    private java.util.List<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle> blockParticles_ =
      java.util.Collections.emptyList();
    private void ensureBlockParticlesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        blockParticles_ = new java.util.ArrayList<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle>(blockParticles_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.twelveoclock.worldeditblockparticles.proto.BlockParticle, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder, dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder> blockParticlesBuilder_;

    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public java.util.List<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle> getBlockParticlesList() {
      if (blockParticlesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blockParticles_);
      } else {
        return blockParticlesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public int getBlockParticlesCount() {
      if (blockParticlesBuilder_ == null) {
        return blockParticles_.size();
      } else {
        return blockParticlesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle getBlockParticles(int index) {
      if (blockParticlesBuilder_ == null) {
        return blockParticles_.get(index);
      } else {
        return blockParticlesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder setBlockParticles(
        int index, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle value) {
      if (blockParticlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockParticlesIsMutable();
        blockParticles_.set(index, value);
        onChanged();
      } else {
        blockParticlesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder setBlockParticles(
        int index, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder builderForValue) {
      if (blockParticlesBuilder_ == null) {
        ensureBlockParticlesIsMutable();
        blockParticles_.set(index, builderForValue.build());
        onChanged();
      } else {
        blockParticlesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder addBlockParticles(dev.twelveoclock.worldeditblockparticles.proto.BlockParticle value) {
      if (blockParticlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockParticlesIsMutable();
        blockParticles_.add(value);
        onChanged();
      } else {
        blockParticlesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder addBlockParticles(
        int index, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle value) {
      if (blockParticlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockParticlesIsMutable();
        blockParticles_.add(index, value);
        onChanged();
      } else {
        blockParticlesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder addBlockParticles(
        dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder builderForValue) {
      if (blockParticlesBuilder_ == null) {
        ensureBlockParticlesIsMutable();
        blockParticles_.add(builderForValue.build());
        onChanged();
      } else {
        blockParticlesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder addBlockParticles(
        int index, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder builderForValue) {
      if (blockParticlesBuilder_ == null) {
        ensureBlockParticlesIsMutable();
        blockParticles_.add(index, builderForValue.build());
        onChanged();
      } else {
        blockParticlesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder addAllBlockParticles(
        java.lang.Iterable<? extends dev.twelveoclock.worldeditblockparticles.proto.BlockParticle> values) {
      if (blockParticlesBuilder_ == null) {
        ensureBlockParticlesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockParticles_);
        onChanged();
      } else {
        blockParticlesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder clearBlockParticles() {
      if (blockParticlesBuilder_ == null) {
        blockParticles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        blockParticlesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public Builder removeBlockParticles(int index) {
      if (blockParticlesBuilder_ == null) {
        ensureBlockParticlesIsMutable();
        blockParticles_.remove(index);
        onChanged();
      } else {
        blockParticlesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder getBlockParticlesBuilder(
        int index) {
      return getBlockParticlesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder getBlockParticlesOrBuilder(
        int index) {
      if (blockParticlesBuilder_ == null) {
        return blockParticles_.get(index);  } else {
        return blockParticlesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public java.util.List<? extends dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder> 
         getBlockParticlesOrBuilderList() {
      if (blockParticlesBuilder_ != null) {
        return blockParticlesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blockParticles_);
      }
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder addBlockParticlesBuilder() {
      return getBlockParticlesFieldBuilder().addBuilder(
          dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.getDefaultInstance());
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder addBlockParticlesBuilder(
        int index) {
      return getBlockParticlesFieldBuilder().addBuilder(
          index, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.getDefaultInstance());
    }
    /**
     * <code>repeated .store.BlockParticle blockParticles = 3;</code>
     */
    public java.util.List<dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder> 
         getBlockParticlesBuilderList() {
      return getBlockParticlesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.twelveoclock.worldeditblockparticles.proto.BlockParticle, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder, dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder> 
        getBlockParticlesFieldBuilder() {
      if (blockParticlesBuilder_ == null) {
        blockParticlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dev.twelveoclock.worldeditblockparticles.proto.BlockParticle, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder, dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder>(
                blockParticles_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        blockParticles_ = null;
      }
      return blockParticlesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:store.BlockParticles)
  }

  // @@protoc_insertion_point(class_scope:store.BlockParticles)
  private static final dev.twelveoclock.worldeditblockparticles.proto.BlockParticles DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.twelveoclock.worldeditblockparticles.proto.BlockParticles();
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticles getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockParticles>
      PARSER = new com.google.protobuf.AbstractParser<BlockParticles>() {
    @java.lang.Override
    public BlockParticles parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockParticles> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockParticles> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.BlockParticles getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

