// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

/**
 * Protobuf type {@code proto.BlockParticle}
 */
public final class BlockParticle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.BlockParticle)
    BlockParticleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockParticle.newBuilder() to construct.
  private BlockParticle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockParticle() {
    particle_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockParticle();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_proto_BlockParticle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_proto_BlockParticle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.class, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder.class);
  }

  public static final int BLOCKPOSITIONBITMASK_FIELD_NUMBER = 1;
  private long blockPositionBitMask_ = 0L;
  /**
   * <code>uint64 blockPositionBitMask = 1;</code>
   * @return The blockPositionBitMask.
   */
  @java.lang.Override
  public long getBlockPositionBitMask() {
    return blockPositionBitMask_;
  }

  public static final int PARTICLE_FIELD_NUMBER = 2;
  private int particle_ = 0;
  /**
   * <code>.proto.Particle particle = 2;</code>
   * @return The enum numeric value on the wire for particle.
   */
  @java.lang.Override public int getParticleValue() {
    return particle_;
  }
  /**
   * <code>.proto.Particle particle = 2;</code>
   * @return The particle.
   */
  @java.lang.Override public dev.twelveoclock.worldeditblockparticles.proto.Particle getParticle() {
    dev.twelveoclock.worldeditblockparticles.proto.Particle result = dev.twelveoclock.worldeditblockparticles.proto.Particle.forNumber(particle_);
    return result == null ? dev.twelveoclock.worldeditblockparticles.proto.Particle.UNRECOGNIZED : result;
  }

  public static final int COUNT_FIELD_NUMBER = 3;
  private int count_ = 0;
  /**
   * <code>uint32 count = 3;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blockPositionBitMask_ != 0L) {
      output.writeUInt64(1, blockPositionBitMask_);
    }
    if (particle_ != dev.twelveoclock.worldeditblockparticles.proto.Particle.PARTICLE_ASH.getNumber()) {
      output.writeEnum(2, particle_);
    }
    if (count_ != 0) {
      output.writeUInt32(3, count_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blockPositionBitMask_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, blockPositionBitMask_);
    }
    if (particle_ != dev.twelveoclock.worldeditblockparticles.proto.Particle.PARTICLE_ASH.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, particle_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, count_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.twelveoclock.worldeditblockparticles.proto.BlockParticle)) {
      return super.equals(obj);
    }
    dev.twelveoclock.worldeditblockparticles.proto.BlockParticle other = (dev.twelveoclock.worldeditblockparticles.proto.BlockParticle) obj;

    if (getBlockPositionBitMask()
        != other.getBlockPositionBitMask()) return false;
    if (particle_ != other.particle_) return false;
    if (getCount()
        != other.getCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCKPOSITIONBITMASK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockPositionBitMask());
    hash = (37 * hash) + PARTICLE_FIELD_NUMBER;
    hash = (53 * hash) + particle_;
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.twelveoclock.worldeditblockparticles.proto.BlockParticle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.BlockParticle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.BlockParticle)
      dev.twelveoclock.worldeditblockparticles.proto.BlockParticleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_proto_BlockParticle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_proto_BlockParticle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.class, dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.Builder.class);
    }

    // Construct using dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      blockPositionBitMask_ = 0L;
      particle_ = 0;
      count_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_proto_BlockParticle_descriptor;
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle getDefaultInstanceForType() {
      return dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.getDefaultInstance();
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle build() {
      dev.twelveoclock.worldeditblockparticles.proto.BlockParticle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle buildPartial() {
      dev.twelveoclock.worldeditblockparticles.proto.BlockParticle result = new dev.twelveoclock.worldeditblockparticles.proto.BlockParticle(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.twelveoclock.worldeditblockparticles.proto.BlockParticle result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.blockPositionBitMask_ = blockPositionBitMask_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.particle_ = particle_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.count_ = count_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.twelveoclock.worldeditblockparticles.proto.BlockParticle) {
        return mergeFrom((dev.twelveoclock.worldeditblockparticles.proto.BlockParticle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.twelveoclock.worldeditblockparticles.proto.BlockParticle other) {
      if (other == dev.twelveoclock.worldeditblockparticles.proto.BlockParticle.getDefaultInstance()) return this;
      if (other.getBlockPositionBitMask() != 0L) {
        setBlockPositionBitMask(other.getBlockPositionBitMask());
      }
      if (other.particle_ != 0) {
        setParticleValue(other.getParticleValue());
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              blockPositionBitMask_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              particle_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              count_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long blockPositionBitMask_ ;
    /**
     * <code>uint64 blockPositionBitMask = 1;</code>
     * @return The blockPositionBitMask.
     */
    @java.lang.Override
    public long getBlockPositionBitMask() {
      return blockPositionBitMask_;
    }
    /**
     * <code>uint64 blockPositionBitMask = 1;</code>
     * @param value The blockPositionBitMask to set.
     * @return This builder for chaining.
     */
    public Builder setBlockPositionBitMask(long value) {

      blockPositionBitMask_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 blockPositionBitMask = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockPositionBitMask() {
      bitField0_ = (bitField0_ & ~0x00000001);
      blockPositionBitMask_ = 0L;
      onChanged();
      return this;
    }

    private int particle_ = 0;
    /**
     * <code>.proto.Particle particle = 2;</code>
     * @return The enum numeric value on the wire for particle.
     */
    @java.lang.Override public int getParticleValue() {
      return particle_;
    }
    /**
     * <code>.proto.Particle particle = 2;</code>
     * @param value The enum numeric value on the wire for particle to set.
     * @return This builder for chaining.
     */
    public Builder setParticleValue(int value) {
      particle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Particle particle = 2;</code>
     * @return The particle.
     */
    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.Particle getParticle() {
      dev.twelveoclock.worldeditblockparticles.proto.Particle result = dev.twelveoclock.worldeditblockparticles.proto.Particle.forNumber(particle_);
      return result == null ? dev.twelveoclock.worldeditblockparticles.proto.Particle.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.Particle particle = 2;</code>
     * @param value The particle to set.
     * @return This builder for chaining.
     */
    public Builder setParticle(dev.twelveoclock.worldeditblockparticles.proto.Particle value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      particle_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Particle particle = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParticle() {
      bitField0_ = (bitField0_ & ~0x00000002);
      particle_ = 0;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>uint32 count = 3;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>uint32 count = 3;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {

      count_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      count_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.BlockParticle)
  }

  // @@protoc_insertion_point(class_scope:proto.BlockParticle)
  private static final dev.twelveoclock.worldeditblockparticles.proto.BlockParticle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.twelveoclock.worldeditblockparticles.proto.BlockParticle();
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.BlockParticle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockParticle>
      PARSER = new com.google.protobuf.AbstractParser<BlockParticle>() {
    @java.lang.Override
    public BlockParticle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockParticle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockParticle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.BlockParticle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

