// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

public interface BlockParticleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:store.BlockParticle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.store.BlockLocation blockLocation = 1;</code>
   * @return Whether the blockLocation field is set.
   */
  boolean hasBlockLocation();
  /**
   * <code>.store.BlockLocation blockLocation = 1;</code>
   * @return The blockLocation.
   */
  dev.twelveoclock.worldeditblockparticles.proto.BlockLocation getBlockLocation();
  /**
   * <code>.store.BlockLocation blockLocation = 1;</code>
   */
  dev.twelveoclock.worldeditblockparticles.proto.BlockLocationOrBuilder getBlockLocationOrBuilder();

  /**
   * <code>.store.Particle particle = 2;</code>
   * @return The enum numeric value on the wire for particle.
   */
  int getParticleValue();
  /**
   * <code>.store.Particle particle = 2;</code>
   * @return The particle.
   */
  dev.twelveoclock.worldeditblockparticles.proto.Particle getParticle();

  /**
   * <code>uint32 count = 3;</code>
   * @return The count.
   */
  int getCount();
}
