// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

public final class ParticlesData {
  private ParticlesData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_BlockParticles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_BlockParticles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_UUID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_UUID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_BlockParticle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_BlockParticle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_BlockLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_BlockLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017particles.proto\022\005store\"p\n\016BlockParticl" +
      "es\022\020\n\010tickRate\030\001 \001(\r\022\036\n\tworldUUID\030\002 \001(\0132" +
      "\013.store.UUID\022,\n\016blockParticles\030\003 \003(\0132\024.s" +
      "tore.BlockParticle\"1\n\004UUID\022\023\n\013mostSigBit" +
      "s\030\001 \001(\004\022\024\n\014leastSigBits\030\002 \001(\004\"n\n\rBlockPa" +
      "rticle\022+\n\rblockLocation\030\001 \001(\0132\024.store.Bl" +
      "ockLocation\022!\n\010particle\030\002 \001(\0162\017.store.Pa" +
      "rticle\022\r\n\005count\030\003 \001(\r\"0\n\rBlockLocation\022\t" +
      "\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\t\n\001z\030\003 \001(\005*\203\026\n\010Part" +
      "icle\022\020\n\014PARTICLE_ASH\020\000\022\030\n\024PARTICLE_BLOCK" +
      "_CRACK\020\001\022\027\n\023PARTICLE_BLOCK_DUST\020\002\022\031\n\025PAR" +
      "TICLE_BLOCK_MARKER\020\003\022\035\n\031PARTICLE_BUBBLE_" +
      "COLUMN_UP\020\004\022\027\n\023PARTICLE_BUBBLE_POP\020\005\022 \n\034" +
      "PARTICLE_CAMPFIRE_COSY_SMOKE\020\006\022\"\n\036PARTIC" +
      "LE_CAMPFIRE_SIGNAL_SMOKE\020\007\022\032\n\026PARTICLE_C" +
      "HERRY_LEAVES\020\010\022\022\n\016PARTICLE_CLOUD\020\t\022\026\n\022PA" +
      "RTICLE_COMPOSTER\020\n\022\032\n\026PARTICLE_CRIMSON_S" +
      "PORE\020\013\022\021\n\rPARTICLE_CRIT\020\014\022\031\n\025PARTICLE_CU" +
      "RRENT_DOWN\020\r\022\035\n\031PARTICLE_DAMAGE_INDICATO" +
      "R\020\016\022\024\n\020PARTICLE_DOLPHIN\020\017\022\032\n\026PARTICLE_DR" +
      "AGON_BREATH\020\020\022\026\n\022PARTICLE_DRIP_LAVA\020\021\022\027\n" +
      "\023PARTICLE_DRIP_WATER\020\022\022$\n PARTICLE_DRIPP" +
      "ING_DRIPSTONE_LAVA\020\023\022%\n!PARTICLE_DRIPPIN" +
      "G_DRIPSTONE_WATER\020\024\022\033\n\027PARTICLE_DRIPPING" +
      "_HONEY\020\025\022#\n\037PARTICLE_DRIPPING_OBSIDIAN_T" +
      "EAR\020\026\022\"\n\036PARTICLE_DUST_COLOR_TRANSITION\020" +
      "\027\022\027\n\023PARTICLE_DUST_PLUME\020\030\022\026\n\022PARTICLE_E" +
      "GG_CRACK\020\031\022\033\n\027PARTICLE_ELECTRIC_SPARK\020\032\022" +
      "\036\n\032PARTICLE_ENCHANTMENT_TABLE\020\033\022\024\n\020PARTI" +
      "CLE_END_ROD\020\034\022\033\n\027PARTICLE_EXPLOSION_HUGE" +
      "\020\035\022\034\n\030PARTICLE_EXPLOSION_LARGE\020\036\022\035\n\031PART" +
      "ICLE_EXPLOSION_NORMAL\020\037\022#\n\037PARTICLE_FALL" +
      "ING_DRIPSTONE_LAVA\020 \022$\n PARTICLE_FALLING" +
      "_DRIPSTONE_WATER\020!\022\031\n\025PARTICLE_FALLING_D" +
      "UST\020\"\022\032\n\026PARTICLE_FALLING_HONEY\020#\022\031\n\025PAR" +
      "TICLE_FALLING_LAVA\020$\022\033\n\027PARTICLE_FALLING" +
      "_NECTAR\020%\022\"\n\036PARTICLE_FALLING_OBSIDIAN_T" +
      "EAR\020&\022\"\n\036PARTICLE_FALLING_SPORE_BLOSSOM\020" +
      "\'\022\032\n\026PARTICLE_FALLING_WATER\020(\022\034\n\030PARTICL" +
      "E_FIREWORKS_SPARK\020)\022\022\n\016PARTICLE_FLAME\020*\022" +
      "\022\n\016PARTICLE_FLASH\020+\022\021\n\rPARTICLE_GLOW\020,\022\033" +
      "\n\027PARTICLE_GLOW_SQUID_INK\020-\022\021\n\rPARTICLE_" +
      "GUST\020.\022\026\n\022PARTICLE_GUST_DUST\020/\022\031\n\025PARTIC" +
      "LE_GUST_EMITTER\0200\022\022\n\016PARTICLE_HEART\0201\022\027\n" +
      "\023PARTICLE_ITEM_CRACK\0202\022\032\n\026PARTICLE_LANDI" +
      "NG_HONEY\0203\022\031\n\025PARTICLE_LANDING_LAVA\0204\022\"\n" +
      "\036PARTICLE_LANDING_OBSIDIAN_TEAR\0205\022\021\n\rPAR" +
      "TICLE_LAVA\0206\022\037\n\033PARTICLE_LEGACY_BLOCK_CR" +
      "ACK\0207\022\036\n\032PARTICLE_LEGACY_BLOCK_DUST\0208\022 \n" +
      "\034PARTICLE_LEGACY_FALLING_DUST\0209\022\033\n\027PARTI" +
      "CLE_MOB_APPEARANCE\020:\022\025\n\021PARTICLE_NAUTILU" +
      "S\020;\022\021\n\rPARTICLE_NOTE\020<\022\023\n\017PARTICLE_PORTA" +
      "L\020=\022\025\n\021PARTICLE_REDSTONE\020>\022\033\n\027PARTICLE_R" +
      "EVERSE_PORTAL\020?\022\023\n\017PARTICLE_SCRAPE\020@\022\031\n\025" +
      "PARTICLE_SCULK_CHARGE\020A\022\035\n\031PARTICLE_SCUL" +
      "K_CHARGE_POP\020B\022\023\n\017PARTICLE_SHRIEK\020C\022\022\n\016P" +
      "ARTICLE_SLIME\020D\022\030\n\024PARTICLE_SMALL_FLAME\020" +
      "E\022\030\n\024PARTICLE_SMOKE_LARGE\020F\022\031\n\025PARTICLE_" +
      "SMOKE_NORMAL\020G\022\023\n\017PARTICLE_NORMAL\020H\022\023\n\017P" +
      "ARTICLE_SNEEZE\020I\022\030\n\024PARTICLE_SNOW_SHOVEL" +
      "\020J\022\025\n\021PARTICLE_SNOWBALL\020K\022\027\n\023PARTICLE_SO" +
      "NICFLAKE\020L\022\021\n\rPARTICLE_SOUL\020M\022\034\n\030PARTICL" +
      "E_SOUL_FIRE_FLAME\020N\022\022\n\016PARTICLE_SPELL\020O\022" +
      "\032\n\026PARTICLE_SPELL_INSTANT\020P\022\026\n\022PARTICLE_" +
      "SPELL_MOB\020Q\022\036\n\032PARTICLE_SPELL_MOB_AMBIEN" +
      "T\020R\022\030\n\024PARTICLE_SPELL_WITCH\020S\022\021\n\rPARTICL" +
      "E_SPIT\020T\022\036\n\032PARTICLE_SPORE_BLOSSOM_AIR\020U" +
      "\022\026\n\022PARTICLE_SQUID_INK\020V\022\026\n\022PARTICLE_SUS" +
      "PENDED\020W\022\034\n\030PARTICLE_SUSPENDED_DEPTH\020X\022\031" +
      "\n\025PARTICLE_SWEEP_ATTACK\020Y\022\022\n\016PARTICLE_TO" +
      "TEM\020Z\022\026\n\022PARTICLE_TOWN_AURA\020[\022$\n PARTICL" +
      "E_TRIAL_SPAWNER_DETECTION\020\\\022\026\n\022PARTICLE_" +
      "VIBRATION\020]\022\033\n\027PARTICLE_VILLAGER_ANGRY\020^" +
      "\022\033\n\027PARTICLE_VILLAGER_HAPPY\020_\022\031\n\025PARTICL" +
      "E_WARPED_SPORE\020`\022\031\n\025PARTICLE_WATER_BUBBL" +
      "E\020a\022\027\n\023PARTICLE_WATER_DROP\020b\022\031\n\025PARTICLE" +
      "_WATER_SPLASH\020c\022\027\n\023PARTICLE_WATER_WAKE\020d" +
      "\022\024\n\020PARTICLE_WAX_OFF\020e\022\023\n\017PARTICLE_WAX_O" +
      "N\020f\022\026\n\022PARTICLE_WHITE_ASH\020g\022\030\n\024PARTICLE_" +
      "WHITE_SMOKE\020hBA\n.dev.twelveoclock.worlde" +
      "ditblockparticles.protoB\rParticlesDataP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_store_BlockParticles_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_store_BlockParticles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_BlockParticles_descriptor,
        new java.lang.String[] { "TickRate", "WorldUUID", "BlockParticles", });
    internal_static_store_UUID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_store_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_UUID_descriptor,
        new java.lang.String[] { "MostSigBits", "LeastSigBits", });
    internal_static_store_BlockParticle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_store_BlockParticle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_BlockParticle_descriptor,
        new java.lang.String[] { "BlockLocation", "Particle", "Count", });
    internal_static_store_BlockLocation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_store_BlockLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_BlockLocation_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
