// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

public interface UUIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UUID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 mostSigBits = 1;</code>
   * @return The mostSigBits.
   */
  long getMostSigBits();

  /**
   * <code>uint64 leastSigBits = 2;</code>
   * @return The leastSigBits.
   */
  long getLeastSigBits();
}
