// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: particles.proto

// Protobuf Java Version: 3.25.2
package dev.twelveoclock.worldeditblockparticles.proto;

/**
 * Protobuf type {@code store.UUID}
 */
public final class UUID extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:store.UUID)
    UUIDOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UUID.newBuilder() to construct.
  private UUID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UUID() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UUID();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_UUID_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_UUID_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.twelveoclock.worldeditblockparticles.proto.UUID.class, dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder.class);
  }

  public static final int MOSTSIGBITS_FIELD_NUMBER = 1;
  private long mostSigBits_ = 0L;
  /**
   * <code>uint64 mostSigBits = 1;</code>
   * @return The mostSigBits.
   */
  @java.lang.Override
  public long getMostSigBits() {
    return mostSigBits_;
  }

  public static final int LEASTSIGBITS_FIELD_NUMBER = 2;
  private long leastSigBits_ = 0L;
  /**
   * <code>uint64 leastSigBits = 2;</code>
   * @return The leastSigBits.
   */
  @java.lang.Override
  public long getLeastSigBits() {
    return leastSigBits_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mostSigBits_ != 0L) {
      output.writeUInt64(1, mostSigBits_);
    }
    if (leastSigBits_ != 0L) {
      output.writeUInt64(2, leastSigBits_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mostSigBits_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, mostSigBits_);
    }
    if (leastSigBits_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, leastSigBits_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.twelveoclock.worldeditblockparticles.proto.UUID)) {
      return super.equals(obj);
    }
    dev.twelveoclock.worldeditblockparticles.proto.UUID other = (dev.twelveoclock.worldeditblockparticles.proto.UUID) obj;

    if (getMostSigBits()
        != other.getMostSigBits()) return false;
    if (getLeastSigBits()
        != other.getLeastSigBits()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOSTSIGBITS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMostSigBits());
    hash = (37 * hash) + LEASTSIGBITS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeastSigBits());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.twelveoclock.worldeditblockparticles.proto.UUID parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.twelveoclock.worldeditblockparticles.proto.UUID prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code store.UUID}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:store.UUID)
      dev.twelveoclock.worldeditblockparticles.proto.UUIDOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_UUID_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_UUID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.twelveoclock.worldeditblockparticles.proto.UUID.class, dev.twelveoclock.worldeditblockparticles.proto.UUID.Builder.class);
    }

    // Construct using dev.twelveoclock.worldeditblockparticles.proto.UUID.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mostSigBits_ = 0L;
      leastSigBits_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.twelveoclock.worldeditblockparticles.proto.ParticlesData.internal_static_store_UUID_descriptor;
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.UUID getDefaultInstanceForType() {
      return dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance();
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.UUID build() {
      dev.twelveoclock.worldeditblockparticles.proto.UUID result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.twelveoclock.worldeditblockparticles.proto.UUID buildPartial() {
      dev.twelveoclock.worldeditblockparticles.proto.UUID result = new dev.twelveoclock.worldeditblockparticles.proto.UUID(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.twelveoclock.worldeditblockparticles.proto.UUID result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mostSigBits_ = mostSigBits_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.leastSigBits_ = leastSigBits_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.twelveoclock.worldeditblockparticles.proto.UUID) {
        return mergeFrom((dev.twelveoclock.worldeditblockparticles.proto.UUID)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.twelveoclock.worldeditblockparticles.proto.UUID other) {
      if (other == dev.twelveoclock.worldeditblockparticles.proto.UUID.getDefaultInstance()) return this;
      if (other.getMostSigBits() != 0L) {
        setMostSigBits(other.getMostSigBits());
      }
      if (other.getLeastSigBits() != 0L) {
        setLeastSigBits(other.getLeastSigBits());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              mostSigBits_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              leastSigBits_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long mostSigBits_ ;
    /**
     * <code>uint64 mostSigBits = 1;</code>
     * @return The mostSigBits.
     */
    @java.lang.Override
    public long getMostSigBits() {
      return mostSigBits_;
    }
    /**
     * <code>uint64 mostSigBits = 1;</code>
     * @param value The mostSigBits to set.
     * @return This builder for chaining.
     */
    public Builder setMostSigBits(long value) {

      mostSigBits_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 mostSigBits = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMostSigBits() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mostSigBits_ = 0L;
      onChanged();
      return this;
    }

    private long leastSigBits_ ;
    /**
     * <code>uint64 leastSigBits = 2;</code>
     * @return The leastSigBits.
     */
    @java.lang.Override
    public long getLeastSigBits() {
      return leastSigBits_;
    }
    /**
     * <code>uint64 leastSigBits = 2;</code>
     * @param value The leastSigBits to set.
     * @return This builder for chaining.
     */
    public Builder setLeastSigBits(long value) {

      leastSigBits_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 leastSigBits = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeastSigBits() {
      bitField0_ = (bitField0_ & ~0x00000002);
      leastSigBits_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:store.UUID)
  }

  // @@protoc_insertion_point(class_scope:store.UUID)
  private static final dev.twelveoclock.worldeditblockparticles.proto.UUID DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.twelveoclock.worldeditblockparticles.proto.UUID();
  }

  public static dev.twelveoclock.worldeditblockparticles.proto.UUID getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UUID>
      PARSER = new com.google.protobuf.AbstractParser<UUID>() {
    @java.lang.Override
    public UUID parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UUID> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UUID> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.twelveoclock.worldeditblockparticles.proto.UUID getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

